services:
  backend:
    build: ./backend
    container_name: ${BACKEND_CONTAINER_NAME:-traefik-dashboard-backend}
    environment:
      - PORT=3001
      - TRAEFIK_LOG_FILE=/logs/access.log
      - USE_MAXMIND=true
      - MAXMIND_DB_PATH=/maxmind/GeoLite2-City.mmdb
      - MAXMIND_FALLBACK_ONLINE=true
      - GOGC=50
      - GOMEMLIMIT=500MiB
    volumes:
      # Mount your Traefik log file or directory here
      - ${TRAEFIK_LOG_PATH:-./logs}:/logs:ro
    ports:
      - "3001:3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: ${FRONTEND_CONTAINER_NAME:-traefik-dashboard-frontend}
    environment:
      - BACKEND_SERVICE=${BACKEND_SERVICE_NAME:-backend}
      - BACKEND_PORT=${BACKEND_PORT:-3001}
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

# Optionally, you can add this service to the same network as Traefik
networks:
  default:
    external:
      name: traefik_network