global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape backend metrics
  - job_name: 'traefik-dashboard-backend'
    static_configs:
      - targets: ['backend:9090']
    metrics_path: '/metrics'

  # Scrape node exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape Traefik metrics if available
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']